Main svc
KoRVeRT/java-explore-with-me pull request #4
Opened 2023-07-08 15:30 UTC by KoRVeRT

2023-07-09 18:28 UTC, kalitva requested changes

2023-07-09 18:28 UTC, kalitva commented on .gitignore
> +/stats-service/stats-client/.gitignore
Я бы рекомендовал оставить только лин гитигнор, корневой

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/dto/CompilationMapper.java
> +    public CompilationDto toCompilationDto(Compilation compilation, List<EventShortDto> list) {
`toCompilationDto --> toDto`

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/service/CompilationService.java
> +    List<CompilationDto> getCompilationsByPinned(Boolean pinned, Integer from, Integer size);
Давай вместо `from` и `size` принимать `Pageable`

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/service/CompilationSpecifications.java
> +public final class CompilationSpecifications {
Нам обязательно нужен этот класс со статическим методом? Можем определить спецификацию в прямо сервисе гед она используется?

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/config/StatsClientConfig.java
> +    }
Давай прямо в поле заинжектим, без использования конструктора

```java
@Value("${stats-server.url}"
private String serverUrl;
```

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/event/model/Location.java
> +    Float lon;
Конечно из контекста понятно что за поля, но все равно, думаю, лучше не сокращать

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/event/service/EventService.java
> +    List<EventFullDto> searchEventsByAdmin(Integer from, Integer size, LocalDateTime rangeStart,
Ого-го, это очень много параметров. Оптимально количество параметров метода -1,2, 3 - уже много, больше 3х уже невозможно читать и использовать

Почитай как можно этого избежать, например использовать objecct pattern - https://www.baeldung.com/java-best-practices-many-parameters-method

2023-07-09 18:28 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/event/service/EventService.java
> +    EventFullDto getEventById(Long eventId, HttpServletRequest request);
`HttpServletRequest` принадлежит строго к слою web и ниже контроллеров не должен опускаться. Достань из него все что нужно, и передавай это в сервис

2023-07-09 18:52 UTC, KoRVeRT commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/dto/CompilationMapper.java
> +    public CompilationDto toCompilationDto(Compilation compilation, List<EventShortDto> list) {
Кратко и смысл не поменялся)

2023-07-09 18:54 UTC, KoRVeRT commented on main-service/src/main/java/ru/practicum/ewm/main/compilation/service/CompilationService.java
> +    List<CompilationDto> getCompilationsByPinned(Boolean pinned, Integer from, Integer size);
Изначально хотел так, но что то отвлекло.)

2023-07-09 21:52 UTC, KoRVeRT commented on main-service/src/main/java/ru/practicum/ewm/main/event/model/Location.java
> +    Float lon;
Если изменить то NewEventDto не сможет преобразовать Location и поля lat и lon будут пустые.

2023-07-10 16:38 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/event/model/Location.java
> +    Float lon;
Можно использовать аннотации джексона, ну да ладно, не принципиально

2023-07-10 16:49 UTC, kalitva approved these changes

2023-07-10 16:49 UTC, kalitva commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Если не знаешь что значит SNAPSHOT в версии, погугли

2023-07-10 16:49 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/api/UserController.java
> +                                                                            eventRequestStatusUpdateRequest) {
Это автоформатирование так сделало? Лучше не разбивать определение параметра, не очень удобно читать

2023-07-10 16:49 UTC, kalitva commented on main-service/src/main/java/ru/practicum/ewm/main/config/JsonTimeFormatConfig.java
> +            builder.deserializers(new LocalDateTimeDeserializer(DateTimeFormatter.ofPattern(DATE_TIME_FORMAT)));
```java
builder.simpleDateFormat(DATE_TIME_FORMAT)
            .serializers(new LocalDateSerializer(DateTimeFormatter.ofPattern(DATE_FORMAT)))
            .serializers(new LocalDateTimeSerializer(DateTimeFormatter.ofPattern(DATE_TIME_FORMAT)))
            .deserializers(new LocalDateDeserializer(DateTimeFormatter.ofPattern(DATE_FORMAT)))
            .deserializers(new LocalDateTimeDeserializer(DateTimeFormatter.ofPattern(DATE_TIME_FORMAT)));
```

А так этот билдер не умеет разве?

2023-07-10 16:49 UTC, kalitva commented on stats-service/stats-dto/pom.xml
> +            <artifactId>tomcat-embed-core</artifactId>
А это зачем? Спринг бут же имеет встроенный томкат...

2023-07-10 17:54 UTC, KoRVeRT commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Спасибо ознакомился.

2023-07-10 17:57 UTC, KoRVeRT commented on main-service/src/main/java/ru/practicum/ewm/main/api/UserController.java
> +                                                                            eventRequestStatusUpdateRequest) {
Нет это я так коряво сделал, учту спасибо.

2023-07-10 18:05 UTC, KoRVeRT commented on main-service/src/main/java/ru/practicum/ewm/main/event/model/Location.java
> +    Float lon;
Не подумал об этом, сделано.

2023-07-10 19:27 UTC, merged